# Generated by Django 3.2.8 on 2021-10-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20211024_0744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='auction',
            name='creation_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
