# Generated by Django 3.2.8 on 2021-10-25 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211025_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
