# Generated by Django 3.2.8 on 2021-10-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
