# Generated by Django 3.2.8 on 2021-12-07 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
